services:
  nvil:
    container_name: ${NVIL_CONTAINER_NAME:-nvil}
    image: ${NVIL_IMAGE:-ghcr.io/thomaschampagne/nvil-full:latest}
    hostname: ${NVIL_CONTAINER_NAME:-nvil}
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /home/smith/workspace
    volumes:
      - nvil-home-data:/home/smith
      - .:/home/smith/workspace
    network_mode: host
    cap_add:
      - NET_RAW
    stdin_open: true
    tty: true

volumes:
  nvil-home-data:
    name: ${NVIL_HOME_DATA_NAME:-default-nvil-home-data}