# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  nvil:
    container_name: ${NVIL_CONTAINER_NAME:-nvil}
    image: ${NVIL_IMAGE:-ghcr.io/thomaschampagne/nvil-full:latest}
    hostname: ${NVIL_CONTAINER_NAME:-nvil}
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /workspace
    volumes:
      - .:/workspace:delegated
    network_mode: host
    cap_add:
      - NET_RAW
    stdin_open: true
    tty: true
