# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  nvil:
    container_name: dev-core
    image: dev-core:latest
    hostname: dev-core
    restart: unless-stopped
    environment:
      - NVIL_GIT_USER_NAME="Thomas Champagne"
      - NVIL_GIT_USER_EMAIL="th.champagne@gmail.com"
      - NVIL_DEFAULT_EDITOR=hx
      - TZ=Europe/Paris
    working_dir: /home/smith/workspace
    volumes:
      - /mnt/wslg/runtime-dir/wayland-0:/run/user/smith/wayland-0:ro # Required to get full copy/paste support through wayland (helix needs it)
      - nvil-home-data:/home/smith
      - ..:/home/smith/workspace
    network_mode: host
    cap_add:
      - NET_RAW
    stdin_open: true
    tty: true

volumes:
  nvil-home-data:
    name: dev-core-nvil-home-data
